[2024-11-17T02:07:19.896+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T02:07:19.914+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: criar_tabelas.inserir_dados_historico manual__2024-11-17T02:05:54.399170+00:00 [queued]>
[2024-11-17T02:07:19.922+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: criar_tabelas.inserir_dados_historico manual__2024-11-17T02:05:54.399170+00:00 [queued]>
[2024-11-17T02:07:19.922+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-17T02:07:19.933+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): inserir_dados_historico> on 2024-11-17 02:05:54.399170+00:00
[2024-11-17T02:07:19.943+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=626) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T02:07:19.945+0000] {standard_task_runner.py:72} INFO - Started process 628 to run task
[2024-11-17T02:07:19.946+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'criar_tabelas', 'inserir_dados_historico', 'manual__2024-11-17T02:05:54.399170+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmppzzy_9ii']
[2024-11-17T02:07:19.947+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask inserir_dados_historico
[2024-11-17T02:07:19.991+0000] {task_command.py:467} INFO - Running <TaskInstance: criar_tabelas.inserir_dados_historico manual__2024-11-17T02:05:54.399170+00:00 [running]> on host bfeda1f9cf11
[2024-11-17T02:07:20.268+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='criar_tabelas' AIRFLOW_CTX_TASK_ID='inserir_dados_historico' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T02:05:54.399170+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T02:05:54.399170+00:00'
[2024-11-17T02:07:20.268+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-17T02:07:20.268+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-17T02:07:20.269+0000] {logging_mixin.py:190} INFO - Current task name:inserir_dados_historico state:running start_date:2024-11-17 02:07:19.914624+00:00
[2024-11-17T02:07:20.269+0000] {logging_mixin.py:190} INFO - Dag name:criar_tabelas and current dag run status:running
[2024-11-17T02:07:20.269+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T02:07:20.396+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriel/workspace/airflow-docker/dags/etl.py", line 274, in inserir_dados_historico
    cursor.execute(insert_query, (
psycopg2.errors.DatatypeMismatch: column "date" is of type bigint but expression is of type timestamp without time zone
LINE 4:                 ) VALUES (1, '2019-11-19T13:00:00'::timestam...
                                     ^
HINT:  You will need to rewrite or cast the expression.

[2024-11-17T02:07:20.405+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-17T02:07:20.405+0000] {logging_mixin.py:190} INFO - Task start:2024-11-17 02:07:19.914624+00:00 end:2024-11-17 02:07:20.405334+00:00 duration:0.49071
[2024-11-17T02:07:20.406+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): inserir_dados_historico> dag:<DAG: criar_tabelas> dagrun:<DagRun criar_tabelas @ 2024-11-17 02:05:54.399170+00:00: manual__2024-11-17T02:05:54.399170+00:00, state:running, queued_at: 2024-11-17 02:05:54.415704+00:00. externally triggered: True>
[2024-11-17T02:07:20.406+0000] {logging_mixin.py:190} INFO - Failure caused by column "date" is of type bigint but expression is of type timestamp without time zone
LINE 4:                 ) VALUES (1, '2019-11-19T13:00:00'::timestam...
                                     ^
HINT:  You will need to rewrite or cast the expression.
[2024-11-17T02:07:20.406+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=criar_tabelas, task_id=inserir_dados_historico, run_id=manual__2024-11-17T02:05:54.399170+00:00, execution_date=20241117T020554, start_date=20241117T020719, end_date=20241117T020720
[2024-11-17T02:07:20.417+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T02:07:20.418+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 112 for task inserir_dados_historico (column "date" is of type bigint but expression is of type timestamp without time zone
LINE 4:                 ) VALUES (1, '2019-11-19T13:00:00'::timestam...
                                     ^
HINT:  You will need to rewrite or cast the expression.
; 628)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gabriel/workspace/airflow-docker/dags/etl.py", line 274, in inserir_dados_historico
    cursor.execute(insert_query, (
psycopg2.errors.DatatypeMismatch: column "date" is of type bigint but expression is of type timestamp without time zone
LINE 4:                 ) VALUES (1, '2019-11-19T13:00:00'::timestam...
                                     ^
HINT:  You will need to rewrite or cast the expression.

[2024-11-17T02:07:20.440+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-17T02:07:20.459+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T02:07:20.462+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
